<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'nama' => 'Super Admin',
            'role' => 'admin',
            'identitas' => 123456,
            'password' => Hash::make('admin'),
            'kategori' => 'Admin',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        $user_mahasiswa = [
        [
            'nama' => 'Mutiara Dwi Jayanti',
            'role' => 'mahasiswa',
            'identitas' => 2110501007,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'SBMPTN',
            'status' => 'active',
            'angkatan_tahun' => 2021,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 90,
            'ipk' => 3.86,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Arwa Althifal Suhermanja',
            'role' => 'mahasiswa',
            'identitas' => 2110501006,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'SBMPTN',
            'status' => 'active',
            'angkatan_tahun' => 2020,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 115,
            'ipk' => 3.65,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Krisna Yuda Nugraha',
            'role' => 'mahasiswa',
            'identitas' => 2110501005,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'SBMPTN',
            'status' => 'active',
            'angkatan_tahun' => 2020,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 135,
            'ipk' => 3.89,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Herzita Saffana',
            'role' => 'mahasiswa',
            'identitas' => 2110501054,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'SBMPTN',
            'status' => 'active',
            'angkatan_tahun' => 2021,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 95,
            'ipk' => 3.70,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Viola Viciani',
            'role' => 'mahasiswa',
            'identitas' => 2110501011,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'SBMPTN',
            'status' => 'active',
            'angkatan_tahun' => 2021,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 98,
            'ipk' => 3.50,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Ali Hakim Alfaroshi',
            'role' => 'mahasiswa',
            'identitas' => 2110501013,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'Mandiri',
            'status' => 'active',
            'angkatan_tahun' => 2020,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 145,
            'ipk' => 3.60,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Salsabila Az Zahra Ruswandi',
            'role' => 'mahasiswa',
            'identitas' => 2110501014,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'Mandiri',
            'status' => 'active',
            'angkatan_tahun' => 2020,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 149,
            'ipk' => 3.96,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Muhammad Farhan',
            'role' => 'mahasiswa',
            'identitas' => 2110501015,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'Mandiri',
            'status' => 'active',
            'angkatan_tahun' => 2022,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 80,
            'ipk' => 3.84,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Arga Pratama',
            'role' => 'mahasiswa',
            'identitas' => 2110501016,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'Mandiri',
            'status' => 'active',
            'angkatan_tahun' => 2019,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 147,
            'ipk' => 3.67,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'nama' => 'Muhammad Raikhan Fadhilah',
            'role' => 'mahasiswa',
            'identitas' => 2110501017,
            'password' => Hash::make('mahasiswa'),
            'kategori' => 'SBMPTN',
            'status' => 'active',
            'angkatan_tahun' => 2019,
            'prodi' => 'Teknik Informatika',
            'sks_ditempuh' => 130,
            'ipk' => 3.42,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ];

        $users = [
            
            // --------------------------------------------------------
            // DOSEN
            // Business Informatics
            [
                'nama' => 'Anita Muliawati, S.Kom., MTI',
                'role' => 'dosen',
                'identitas' => 197005212021212002,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0321057001',
                'jenis_kelamin' => 'female',
                'email' => 'anitamuliawati@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Artika Arista, S. Kom, MMSI',
                'role' => 'dosen',
                'identitas' => 199309082020122022,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '-',
                'jenis_kelamin' => 'female',
                'email' => '-',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Erly Krisnanik, S.Kom.,MM',
                'role' => 'dosen',
                'identitas' => 197409082021212003,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0308097401',
                'jenis_kelamin' => 'female',
                'email' => 'erlykrisnanik@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tri Rahayu, S.Kom., MM',
                'role' => 'dosen',
                'identitas' => 197711052021212001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0305117701',
                'jenis_kelamin' => 'female',
                'email' => 'trirahayu@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'M. Bayu Wibisono, S.Kom.,MM',
                'role' => 'dosen',
                'identitas' => 197505262021211003,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0326057502',
                'jenis_kelamin' => 'male',
                'email' => 'bayu.wibisono@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'nama' => 'Dra.Intan Hesti Indriana, SE., MM',
                'role' => 'dosen',
                'identitas' => 196209021989032001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0002096210',
                'jenis_kelamin' => 'female',
                'email' => 'hesti@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor Kepala 400',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Zatin Niqotaini, S.Tr.Kom., M.Kom',
                'role' => 'dosen',
                'identitas' => 199302102022032007,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0410029301',
                'jenis_kelamin' => 'female',
                'email' => '-',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rifka Dwi Amalia, S.Pd., M.Kom',
                'role' => 'dosen',
                'identitas' => 199001092022032005,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0009019007',
                'jenis_kelamin' => 'female',
                'email' => '-',
                'no_hp' => '-',
                'pangkat_akademik' => 'Tenaga Pengajar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Catur Nugrahaeni Puspita Dewi, S.Kom., M.Kom',
                'role' => 'dosen',
                'identitas' => 198708232021212002,
                'password' => Hash::make('dosen'),
                'kategori' => 'Business Informatics',
                'status' => 'active',
                'NIDN' => '0023088701',
                'jenis_kelamin' => 'female',
                'email' => 'catur.nugrahaeni@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Programming Languanges
            [
                'nama' => 'Ruth Mariana Bunga Wadu, S.Kom., MMSI',
                'role' => 'dosen',
                'identitas' => 198803292018032001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0429038801',
                'jenis_kelamin' => 'female',
                'email' => 'ruthbungawadu@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Radinal Setyadinsa, S.Pd., M.T.I',
                'role' => 'dosen',
                'identitas' => 198901292022031003,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0029018909',
                'jenis_kelamin' => 'male',
                'email' => 'radinalsetyadinsa@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Tenaga Pengajar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Andika Octa Indarso, M. MSI',
                'role' => 'dosen',
                'identitas' => 198406032018031001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0028088408',
                'jenis_kelamin' => 'male',
                'email' => 'andyocta@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rio Wirawan, S.Kom., MMSI',
                'role' => 'dosen',
                'identitas' => 198610202019031006,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0420018601',
                'jenis_kelamin' => 'male',
                'email' => 'rio.wirawan@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'I Wayan Widi P.,S.Kom., MTI',
                'role' => 'dosen',
                'identitas' => 215121129,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0025068104',
                'jenis_kelamin' => 'male',
                'email' => 'wayan.widi@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Musthofa Galih Pradana, M.Kom',
                'role' => 'dosen',
                'identitas' => 199608052022031006,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0505089601',
                'jenis_kelamin' => 'male',
                'email' => 'musthofagalihpradana@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nurul Afifah Arifuddin, S.Pd., M.T',
                'role' => 'dosen',
                'identitas' => 199311072022032019,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0324068203',
                'jenis_kelamin' => 'female',
                'email' => 'theresiawati@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Theresiawati, S.Kom.,M.TI',
                'role' => 'dosen',
                'identitas' => 198206242021212005,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0324068203',
                'jenis_kelamin' => 'female',
                'email' => 'theresiawati@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Noor Falih, S.Kom., M.T',
                'role' => 'dosen',
                'identitas' => 198907152018031001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '1015078902',
                'jenis_kelamin' => 'male',
                'email' => 'falih@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kharisma Wiati Gusti, M.T',
                'role' => 'dosen',
                'identitas' => 199006192022032007,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0019069005',
                'jenis_kelamin' => 'female',
                'email' => 'kharismawiatigusti@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Tenaga Pengajar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ichsan Mardani, S.Kom, M.Sc',
                'role' => 'dosen',
                'identitas' => 215121125,
                'password' => Hash::make('dosen'),
                'kategori' => 'Programming Languanges',
                'status' => 'active',
                'NIDN' => '0003038508',
                'jenis_kelamin' => 'male',
                'email' => 'mardani300@gmail.com',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Information Science
            [
                'nama' => 'Dr. Bambang Saras Yulistiawan, S.T., M.Kom',
                'role' => 'dosen',
                'identitas' => 197807072009121004,
                'password' => Hash::make('dosen'),
                'kategori' => 'Information Science',
                'status' => 'active',
                'NIDN' => '0107077801',
                'jenis_kelamin' => 'male',
                'email' => '-',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sarika M.Kom.',
                'role' => 'dosen',
                'identitas' => 198711092018032001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Information Science',
                'status' => 'active',
                'NIDN' => '0009118706',
                'jenis_kelamin' => 'female',
                'email' => 'sarika.afrizal@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nindy Irzavika, S.SI., M.T',
                'role' => 'dosen',
                'identitas' => 199206172022032019,
                'password' => Hash::make('dosen'),
                'kategori' => 'Information Science',
                'status' => 'active',
                'NIDN' => '0017069210',
                'jenis_kelamin' => 'female',
                'email' => 'nindyirzavika@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Neny Rosmawarni, M.Kom',
                'role' => 'dosen',
                'identitas' => 198701122022032001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Information Science',
                'status' => 'active',
                'NIDN' => '0312018701',
                'jenis_kelamin' => 'female',
                'email' => 'nenyrosmawarni@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Helena Nurramdhani Irmanda, S.Pd, M.Kom',
                'role' => 'dosen',
                'identitas' => 199203312018032001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Information Science',
                'status' => 'active',
                'NIDN' => '0031039202',
                'jenis_kelamin' => 'female',
                'email' => 'helenairmanda@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Iin Ernawati S.Kom., M.Si',
                'role' => 'dosen',
                'identitas' => 197601022021212004,
                'password' => Hash::make('dosen'),
                'kategori' => 'Information Science',
                'status' => 'active',
                'NIDN' => '0302017601',
                'jenis_kelamin' => 'female',
                'email' => 'iinernawati@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nur Hafifah Matondang, S.Kom, MM',
                'role' => 'dosen',
                'identitas' => 488101109771,
                'password' => Hash::make('dosen'),
                'kategori' => 'Information Science',
                'status' => 'active',
                'NIDN' => '0010108804',
                'jenis_kelamin' => 'female',
                'email' => 'nurhafifahmatondang@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Artificial Intelligence
            [
                'nama' => 'Muhammad Adrezo, S.Kom.,M.Sc',
                'role' => 'dosen',
                'identitas' => 199404042022031013,
                'password' => Hash::make('dosen'),
                'kategori' => 'Artificial Intelligence',
                'status' => 'active',
                'NIDN' => '0004049403',
                'jenis_kelamin' => 'male',
                'email' => 'muhammad.adrezo@gmail.com',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Muhammad Panji Muslim, S.Pd., M.Kom',
                'role' => 'dosen',
                'identitas' => 199308312022031007,
                'password' => Hash::make('dosen'),
                'kategori' => 'Artificial Intelligence',
                'status' => 'active',
                'NIDN' => '0031089303',
                'jenis_kelamin' => 'male',
                'email' => 'muhammadpanji@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nurul Chamidah, S.Kom, M.Kom',
                'role' => 'dosen',
                'identitas' => 198909302018032002,
                'password' => Hash::make('dosen'),
                'kategori' => 'Artificial Intelligence',
                'status' => 'active',
                'NIDN' => '030098907',
                'jenis_kelamin' => 'female',
                'email' => 'nurul.chamidah@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mayanda Mega Santoni, S.Komp, M.Kom',
                'role' => 'dosen',
                'identitas' => 199005252018032001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Artificial Intelligence',
                'status' => 'active',
                'NIDN' => '0025059002',
                'jenis_kelamin' => 'female',
                'email' => 'nurul.chamidah@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Computer Graphics
            [
                'nama' => 'Desta Sandya Prasvita, S.Komp.,M.Kom',
                'role' => 'dosen',
                'identitas' => 198712032019031010,
                'password' => Hash::make('dosen'),
                'kategori' => 'Computer Graphics',
                'status' => 'active',
                'NIDN' => '0303128702',
                'jenis_kelamin' => 'male',
                'email' => 'desta.sandya@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Computer Security and Reliability
            [
                'nama' => 'Novi Trisman Hadi, S.Pd., M.Kom',
                'role' => 'dosen',
                'identitas' => 199211032022031007,
                'password' => Hash::make('dosen'),
                'kategori' => 'Computer Security and Reliability',
                'status' => 'active',
                'NIDN' => '0003119209',
                'jenis_kelamin' => 'male',
                'email' => 'novitrismanhadi@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bambang Tri Wahyono, S.Kom., M.Si',
                'role' => 'dosen',
                'identitas' => 197403022021211006,
                'password' => Hash::make('dosen'),
                'kategori' => 'Computer Security and Reliability',
                'status' => 'active',
                'NIDN' => '0320037401',
                'jenis_kelamin' => 'male',
                'email' => 'bambang.triwahyono@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hamonangan Kinantan P., S.T, MT',
                'role' => 'dosen',
                'identitas' => 196109301993031001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Computer Security and Reliability',
                'status' => 'active',
                'NIDN' => '0002088502',
                'jenis_kelamin' => 'male',
                'email' => 'hamonangan.kp@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Indra Permana Solihin, S.Kom, M.Kom',
                'role' => 'dosen',
                'identitas' => 198308092021211001,
                'password' => Hash::make('dosen'),
                'kategori' => 'Computer Security and Reliability',
                'status' => 'active',
                'NIDN' => '0309088301',
                'jenis_kelamin' => 'male',
                'email' => 'indrapermana@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bayu Hananto, S.Kom, M.Kom',
                'role' => 'dosen',
                'identitas' => 198612042019031010,
                'password' => Hash::make('dosen'),
                'kategori' => 'Computer Security and Reliability',
                'status' => 'active',
                'NIDN' => '0004128602',
                'jenis_kelamin' => 'male',
                'email' => 'bayuhananto@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nurhuda Maulana, S.T., M.T',
                'role' => 'dosen',
                'identitas' => 199306152022031003,
                'password' => Hash::make('dosen'),
                'kategori' => 'Computer Security and Reliability',
                'status' => 'active',
                'NIDN' => '0015069304',
                'jenis_kelamin' => 'male',
                'email' => 'nurhudamaulana@upnvj.ac.id',
                'no_hp' => '-',
                'pangkat_akademik' => 'Asisten Ahli 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Human Computer Interaction
            [
                'nama' => 'Ika Nurlaili, S.Kom,M.Sc',
                'role' => 'dosen',
                'identitas' => 217121291,
                'password' => Hash::make('dosen'),
                'kategori' => 'Human Computer Interaction',
                'status' => 'active',
                'NIDN' => '0015039301',
                'jenis_kelamin' => 'male',
                'email' => '-',
                'no_hp' => '-',
                'pangkat_akademik' => 'Lektor 300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('users')->insert($users);
        DB::table('users')->insert($user_mahasiswa);
    }
}
